name: Notion Markdown Action

on: 
  push:
    paths:
      - "markdown/**/*.md"

jobs:
  add-notion-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run
        run: node lib/index.js