name: Notion Markdown Action

on: 
  push:
    paths:
      - "memos/**/*.md"

jobs:
  add-notion-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Run
        run: npm run start
        env:
          NOTION_API_KEY: ${{secrets.NOTION_API_KEY}} 
          NOTION_DATABASE_ID: ${{secrets.NOTION_DATABASE_ID}}